title: "Partially functional"
author: "Peter Perhac"
description: "Excellence is never an accident. It is always the result of high intention, sincere effort, and intelligent execution; it represents the wise choice of many alternatives - choice, not chance, determines your destiny. [Aristotle]"
more: "read more Â»"
url: "http://www.perhac.com/blog/"
baseurl: "/blog" # comment out if in root directory

comments:
  disqus: "perhac-blog.disqus.com"
#  isso: "comments.mysite.org"

style:
  body: 'white'
  margin: 0%
  padding: 20%
  nav: "#222"
  articles: 'stripe' # 'light' 'dark' and 'stripe' possible
  uppercase: false

# see http://fontawesome.io/icons/#brand for all possible icons
# notice: squared icons only work if supported by font-awesome

links:
  - github: {url: "https://github.com/PeterPerhac/", square: true}
  - facebook: {url: "https://www.facebook.com/perhac.peter", square: true}
  - google-plus: {url: "https://plus.google.com/+PeterPerhacMComp", square: true}
  - youtube: {url: "http://www.youtube.com/user/Mast3rP3t3r", square: true}

paginate: 5
excerpt_separator: "\n\n\n" # excerpt ends after two blank lines
permalink: pretty
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
gems: [jekyll-feed, jekyll-paginate] # include feed plugin (supported by gh-pages)

