title: "Partially functional"
author: "Peter Perhac"
description: "As I am diving deeper and deeper into the world of functional programming, I decided to keep a blog where I can rant about all sorts of things."
more: "read more Â»"
url: "https://www.perhac.com/blog"
baseurl: "/blog" # comment out if in root directory

comments:
  disqus: "perhac-blog.disqus.com"
#  isso: "comments.mysite.org"

style:
  body: 'white'
  margin: 0%
  padding: 10%
  nav: "#222"
  articles: 'stripe' # 'light' 'dark' and 'stripe' possible
  uppercase: false

# see http://fontawesome.io/icons/#brand for all possible icons
# notice: squared icons only work if supported by font-awesome

links:
  - github: {url: "https://github.com/PeterPerhac/", square: true}
  - facebook: {url: "https://www.facebook.com/perhac.peter", square: true}
  - google-plus: {url: "https://plus.google.com/+PeterPerhacMComp", square: true}
  - stackoverflow: {url: "https://stackoverflow.com/users/81520/peter-perh%C3%A1%C4%8D", square: true}

paginate: 5
excerpt_separator: "\n\n\n\n" # excerpt ends after three blank lines
permalink: pretty
future: false
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}, {scope: {path: "", type: "posts"}, values: {published: false}}]
gems: [jekyll-feed, jekyll-paginate] # include feed plugin (supported by gh-pages)
exclude: ["dem-codez"]
include: [".htaccess"]

